/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.2
 * Generated at: 2018-12-03 08:13:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.adExercise;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class adExercise_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"row no-margin\">\r\n");
      out.write("        <div class=\"col-xl-12\">\r\n");
      out.write("            <!-- Begin Widget -->\r\n");
      out.write("            <div class=\"row widget has-shadow\">\r\n");
      out.write("                <div class=\"widget-header bordered d-flex align-items-center\">\r\n");
      out.write("                    <h2>Calendar</h2>\r\n");
      out.write("                    <div class=\"widget-body\">\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <div class=\"btn-group\" role=\"group\" aria-label=\"Buttons Group\">\r\n");
      out.write("                                <button type=\"button\" class=\"btn btn-info mb-2\">초급</button>\r\n");
      out.write("                                <button type=\"button\" class=\"btn btn-warning mb-2\">중급</button>\r\n");
      out.write("                                <button type=\"button\" class=\"btn btn-danger mb-2\">고급</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- End Widget Header -->\r\n");
      out.write("                <!-- Begin Widget Body -->\r\n");
      out.write("                <div class=\"widget-body\">\r\n");
      out.write("                    <!-- Begin Calendar -->\r\n");
      out.write("                    <div id=\"demo-calendar\"></div>\r\n");
      out.write("                    <!-- End Calendar -->\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- End Widget Body -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- End Widget -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End Col -->\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t(function ($) {\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('.circle-orders').circleProgress({\r\n");
      out.write("\t\t\tvalue: 0.43,\r\n");
      out.write("\t\t\tsize: 120,\r\n");
      out.write("\t\t\tstartAngle: -Math.PI / 2,\r\n");
      out.write("\t\t\tthickness: 6,\r\n");
      out.write("\t\t\tlineCap: 'round',\r\n");
      out.write("\t\t\temptyFill: '#e4e8f0',\r\n");
      out.write("\t\t\tfill: {\r\n");
      out.write("\t\t\t\tgradient: ['#0087a4', '#08a6c3']\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}).on('circle-animation-progress', function (event, progress) {\r\n");
      out.write("\t\t\t$(this).find('.percent-orders').html(Math.round(43 * progress) + '<i>%</i>');\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t    // ------------------------------------------------------- //\r\n");
      out.write("\t    // Calendar\r\n");
      out.write("\t    // ------------------------------------------------------ //\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t// page is ready\r\n");
      out.write("\t\t\t$('#demo-calendar').fullCalendar({\r\n");
      out.write("\t\t\t\t// emphasizes business hours\r\n");
      out.write("\t\t\t\tbusinessHours: true,\r\n");
      out.write("\t\t\t\tdefaultView: 'month',\r\n");
      out.write("\t\t\t\t// event dragging & resizing\r\n");
      out.write("\t\t\t\teditable: true,\r\n");
      out.write("\t\t\t\t// header\r\n");
      out.write("\t\t\t\theader: {\r\n");
      out.write("\t\t\t\t\tleft: 'title',\r\n");
      out.write("\t\t\t\t\tcenter: 'month,agendaWeek,agendaDay',\r\n");
      out.write("\t\t\t\t\tright: 'today prev,next'\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tevents: [\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\ttitle: '어께',\r\n");
      out.write("\t\t\t\t\t\tdescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras eu pellentesque nibh. In nisl nulla, convallis ac nulla eget, pellentesque pellentesque magna.',\r\n");
      out.write("\t\t\t\t\t\tstart: '2018-11-29',\r\n");
      out.write("\t\t\t\t\t\tend: '2018-11-30',\r\n");
      out.write("\t\t\t\t\t\tclassName: 'fc-bg-violet',\r\n");
      out.write("\t\t\t\t\t\ticon : \"calendar\"\r\n");
      out.write("\t\t\t\t\t}, \r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\ttitle: '하체',\r\n");
      out.write("\t\t\t\t\t\tdescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras eu pellentesque nibh. In nisl nulla, convallis ac nulla eget, pellentesque pellentesque magna.',\r\n");
      out.write("\t\t\t\t\t\tstart: '2018-11-29',\r\n");
      out.write("\t\t\t\t\t\tend: '2018-11-30',\r\n");
      out.write("\t\t\t\t\t\tclassName: 'fc-bg-default',\r\n");
      out.write("\t\t\t\t\t\ticon : \"child\"\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\ttitle: '등',\r\n");
      out.write("\t\t\t\t\t\tdescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras eu pellentesque nibh. In nisl nulla, convallis ac nulla eget, pellentesque pellentesque magna.',\r\n");
      out.write("\t\t\t\t\t\tstart: '2018-11-29',\r\n");
      out.write("\t\t\t\t\t\tend: '2018-11-30',\r\n");
      out.write("\t\t\t\t\t\tclassName: 'fc-bg-default',\r\n");
      out.write("\t\t\t\t\t\ticon : \"birthday-cake\"\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\ttitle: 'test',\r\n");
      out.write("\t\t\t\t\t\tdescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras eu pellentesque nibh. In nisl nulla, convallis ac nulla eget, pellentesque pellentesque magna.',\r\n");
      out.write("\t\t\t\t\t\tstart: '2018-11-29',\r\n");
      out.write("\t\t\t\t\t\tend: '2018-11-30',\r\n");
      out.write("\t\t\t\t\t\tclassName: 'fc-bg-default',\r\n");
      out.write("\t\t\t\t\t\ticon : \"birthday-cake\"\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t],\r\n");
      out.write("\t\t\t\teventRender: function(event, element) {\r\n");
      out.write("\t\t\t\t\tif(event.icon){          \r\n");
      out.write("\t\t\t\t\t\telement.find(\".fc-title\").prepend(\"<i class='la la-\"+event.icon+\"'></i>\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t  },\r\n");
      out.write("\t\t\t\teventClick: function(event, jsEvent, view) {\r\n");
      out.write("\t\t\t\t        $('.event-icon').html(\"<i class='la la-\"+event.icon+\"'></i>\");\r\n");
      out.write("\t\t\t\t\t\t$('.event-title').html(event.title);\r\n");
      out.write("\t\t\t\t\t\t$('.event-body').html(event.description);\r\n");
      out.write("\t\t\t\t\t\t$('.eventUrl').attr('href',event.url);\r\n");
      out.write("\t\t\t\t\t\t$('#modal-view-event').modal();\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t    // ------------------------------------------------------- //\r\n");
      out.write("\t    // Files\r\n");
      out.write("\t    // ------------------------------------------------------ //\r\n");
      out.write("\t\t$('.widget20').owlCarousel({\r\n");
      out.write("\t\t\tdots: true,\r\n");
      out.write("\t\t\tnav: false,\r\n");
      out.write("\t\t\tloop: true,\r\n");
      out.write("\t\t\tresponsiveClass:true,\r\n");
      out.write("\t\t\tnavText: ['<i class=\"la la-angle-left\" aria-hidden=\"true\"></i>', '<i class=\"la la-angle-right\" aria-hidden=\"true\"></i>'],\r\n");
      out.write("\t\t\tresponsive:{\r\n");
      out.write("\t\t\t\t0:{\r\n");
      out.write("\t\t\t\t\titems:1\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t600:{\r\n");
      out.write("\t\t\t\t\titems:2\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t1000:{\r\n");
      out.write("\t\t\t\t\titems:2\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t})(jQuery);\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
