/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.2
 * Generated at: 2018-12-03 07:54:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<div class=\"content-wrap\">\r\n");
      out.write("\t<div class=\"container clearfix\">\r\n");
      out.write("\t\t<div class=\"row clearfix\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-xl-5\">\r\n");
      out.write("\t\t\t\t<div class=\"heading-block topmargin\">\r\n");
      out.write("\t\t\t\t\t<h1>한달 4만으로<br>매일 매일 당신을 체크합니다.</h1>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<p class=\"lead\">애니 픽트는 항상 당신을 위해 움직입니다. <br>하루 1300원의 요금!  최대의 서비스! <br> 지금 바로 신청하세요!</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-xl-7\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div style=\"position: relative; margin-bottom: -60px;\" class=\"ohidden\" data-height-xl=\"426\" data-height-lg=\"567\" data-height-md=\"470\" data-height-md=\"287\" data-height-xs=\"183\">\r\n");
      out.write("\t\t\t\t\t<img src=\"images/services/main-fbrowser.png\" style=\"position: absolute; top: 0; left: 0;\" data-animate=\"fadeInUp\" data-delay=\"100\" alt=\"Chrome\">\r\n");
      out.write("\t\t\t\t\t<img src=\"images/services/main-fmobile.png\" style=\"position: absolute; top: 0; left: 0;\" data-animate=\"fadeInUp\" data-delay=\"400\" alt=\"iPad\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"section nobottommargin\" style=\"max-width: 1170px;margin: auto;background-color: #ffffff;\">\r\n");
      out.write("\t\t<div class=\"col_one_third\">\r\n");
      out.write("\t\t\t<div class=\"feature-box fbox-small fbox-plain\" data-animate=\"fadeIn\">\r\n");
      out.write("\t\t\t\t<div class=\"fbox-icon\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"><i class=\"icon-line-monitor\"></i></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<h3>Responsive Layout</h3>\r\n");
      out.write("\t\t\t\t<p>Powerful Layout with Responsive functionality that can be adapted to any screen size.</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"col_one_third\">\r\n");
      out.write("\t\t\t<div class=\"feature-box fbox-small fbox-plain\" data-animate=\"fadeIn\" data-delay=\"200\">\r\n");
      out.write("\t\t\t\t<div class=\"fbox-icon\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"><i class=\"icon-line-eye\"></i></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<h3>Retina Ready Graphics</h3>\r\n");
      out.write("\t\t\t\t<p>Looks beautiful &amp; ultra-sharp on Retina Displays with Retina Icons, Fonts &amp; Images.</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"col_one_third col_last\">\r\n");
      out.write("\t\t\t<div class=\"feature-box fbox-small fbox-plain\" data-animate=\"fadeIn\" data-delay=\"400\">\r\n");
      out.write("\t\t\t\t<div class=\"fbox-icon\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"><i class=\"icon-line-star\"></i></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<h3>Powerful Performance</h3>\r\n");
      out.write("\t\t\t\t<p>Optimized code that are completely customizable and deliver unmatched fast performance.</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"clear\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"col_one_third\">\r\n");
      out.write("\t\t\t<div class=\"feature-box fbox-small fbox-plain\" data-animate=\"fadeIn\" data-delay=\"600\">\r\n");
      out.write("\t\t\t\t<div class=\"fbox-icon\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"><i class=\"icon-line-play\"></i></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<h3>HTML5 Video</h3>\r\n");
      out.write("\t\t\t\t<p>Canvas provides support for Native HTML5 Videos that can be added to a Full Width Background.</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"col_one_third\">\r\n");
      out.write("\t\t\t<div class=\"feature-box fbox-small fbox-plain\" data-animate=\"fadeIn\" data-delay=\"800\">\r\n");
      out.write("\t\t\t\t<div class=\"fbox-icon\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"><i class=\"icon-params\"></i></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<h3>Parallax Support</h3>\r\n");
      out.write("\t\t\t\t<p>Display your Content attractively using Parallax Sections that have unlimited customizable areas.</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"col_one_third col_last\">\r\n");
      out.write("\t\t\t<div class=\"feature-box fbox-small fbox-plain\" data-animate=\"fadeIn\" data-delay=\"1000\">\r\n");
      out.write("\t\t\t\t<div class=\"fbox-icon\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"><i class=\"icon-line-circle-check\"></i></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<h3>Endless Possibilities</h3>\r\n");
      out.write("\t\t\t\t<p>Complete control on each &amp; every element that provides endless customization possibilities.</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"clear\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"col_one_third bottommargin-sm\">\r\n");
      out.write("\t\t\t<div class=\"feature-box fbox-small fbox-plain\" data-animate=\"fadeIn\" data-delay=\"600\">\r\n");
      out.write("\t\t\t\t<div class=\"fbox-icon\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"><i class=\"icon-bulb\"></i></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<h3>Light &amp; Dark Color Schemes</h3>\r\n");
      out.write("\t\t\t\t<p>Change your Website's Primary Scheme instantly by simply adding the dark class to the body.</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"col_one_third bottommargin-sm\">\r\n");
      out.write("\t\t\t<div class=\"feature-box fbox-small fbox-plain\" data-animate=\"fadeIn\" data-delay=\"800\">\r\n");
      out.write("\t\t\t\t<div class=\"fbox-icon\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"><i class=\"icon-heart2\"></i></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<h3>Boxed &amp; Wide Layouts</h3>\r\n");
      out.write("\t\t\t\t<p>Stretch your Website to the Full Width or make it boxed to surprise your visitors.</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"col_one_third bottommargin-sm col_last\">\r\n");
      out.write("\t\t\t<div class=\"feature-box fbox-small fbox-plain\" data-animate=\"fadeIn\" data-delay=\"1000\">\r\n");
      out.write("\t\t\t\t<div class=\"fbox-icon\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"><i class=\"icon-note\"></i></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<h3>Extensive Documentation</h3>\r\n");
      out.write("\t\t\t\t<p>We have covered each &amp; everything in our Documentation including Videos &amp; Screenshots.</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"section parallax dark nobottommargin\" style=\"background-image: url('images/services/home-testi-bg.jpg'); padding: 100px 0;\" data-bottom-top=\"background-position:0px 300px;\" data-top-bottom=\"background-position:0px -300px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"heading-block center\">\r\n");
      out.write("\t\t\t\t<h3>왜 애니핏이 필요하다고 말하는가?</h3>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"fslider testimonial testimonial-full\" data-animation=\"fade\" data-arrows=\"false\">\r\n");
      out.write("\t\t\t\t<div class=\"flexslider\">\r\n");
      out.write("\t\t\t\t\t<div class=\"slider-wrap\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"slide\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"testi-image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\"><img src=\"images/testimonials/3.jpg\" alt=\"Customer Testimonails\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"testi-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>Similique fugit repellendus expedita excepturi iure perferendis provident quia eaque. Repellendus, vero numquam?</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"testi-meta\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tSteve Jobs\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>Apple Inc.</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"slide\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"testi-image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\"><img src=\"images/testimonials/2.jpg\" alt=\"Customer Testimonails\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"testi-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>Natus voluptatum enim quod necessitatibus quis expedita harum provident eos obcaecati id culpa corporis molestias.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"testi-meta\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tCollis Ta'eed\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>Envato Inc.</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"slide\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"testi-image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\"><img src=\"images/testimonials/1.jpg\" alt=\"Customer Testimonails\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"testi-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>Incidunt deleniti blanditiis quas aperiam recusandae consequatur ullam quibusdam cum libero illo rerum!</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"testi-meta\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tJohn Doe\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>XYZ Inc.</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container clearfix\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"heading-block topmargin-lg center\">\r\n");
      out.write("\t\t\t<h2>Even more Feature Rich</h2>\r\n");
      out.write("\t\t\t<span class=\"divcenter\">Philanthropy convener livelihoods, initiative end hunger gender rights local. John Lennon storytelling; advocate, altruism impact catalyst.</span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row bottommargin-sm\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-lg-4 col-md-6 bottommargin\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"feature-box fbox-right topmargin\" data-animate=\"fadeIn\">\r\n");
      out.write("\t\t\t\t\t<div class=\"fbox-icon\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"icon-line-heart\"></i></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<h3>Boxed &amp; Wide Layouts</h3>\r\n");
      out.write("\t\t\t\t\t<p>Stretch your Website to the Full Width or make it boxed to surprise your visitors.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"feature-box fbox-right topmargin\" data-animate=\"fadeIn\" data-delay=\"200\">\r\n");
      out.write("\t\t\t\t\t<div class=\"fbox-icon\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"icon-line-paper\"></i></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<h3>Extensive Documentation</h3>\r\n");
      out.write("\t\t\t\t\t<p>We have covered each &amp; everything in our Docs including Videos &amp; Screenshots.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"feature-box fbox-right topmargin\" data-animate=\"fadeIn\" data-delay=\"400\">\r\n");
      out.write("\t\t\t\t\t<div class=\"fbox-icon\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"icon-line-layers\"></i></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<h3>Parallax Support</h3>\r\n");
      out.write("\t\t\t\t\t<p>Display your Content attractively using Parallax Sections with HTML5 Videos.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-lg-4 d-md-none d-lg-block bottommargin center\">\r\n");
      out.write("\t\t\t\t<img src=\"images/services/iphone7.png\" alt=\"iphone 2\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-lg-4 col-md-6 bottommargin\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"feature-box topmargin\" data-animate=\"fadeIn\">\r\n");
      out.write("\t\t\t\t\t<div class=\"fbox-icon\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"icon-line-power\"></i></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<h3>HTML5 Video</h3>\r\n");
      out.write("\t\t\t\t\t<p>Canvas provides support for Native HTML5 Videos that can be added to a Background.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"feature-box topmargin\" data-animate=\"fadeIn\" data-delay=\"200\">\r\n");
      out.write("\t\t\t\t\t<div class=\"fbox-icon\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"icon-line-check\"></i></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<h3>Endless Possibilities</h3>\r\n");
      out.write("\t\t\t\t\t<p>Complete control on each &amp; every element that provides endless customization.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"feature-box topmargin\" data-animate=\"fadeIn\" data-delay=\"400\">\r\n");
      out.write("\t\t\t\t\t<div class=\"fbox-icon\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><i class=\"icon-bulb\"></i></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<h3>Light &amp; Dark Color Schemes</h3>\r\n");
      out.write("\t\t\t\t\t<p>Change your Website's Primary Scheme instantly by simply adding the dark class.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"row clearfix bottommargin-lg common-height\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"col-lg-3 col-md-6 dark center col-padding\" style=\"background-color: #515875;\">\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<i class=\"i-plain i-xlarge divcenter icon-line2-directions\"></i>\r\n");
      out.write("\t\t\t\t<div class=\"counter counter-lined\"><span data-from=\"100\" data-to=\"846\" data-refresh-interval=\"50\" data-speed=\"2000\"></span>K</div>\r\n");
      out.write("\t\t\t\t<h5>등록된 운동법</h5>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"col-lg-3 col-md-6 dark center col-padding\" style=\"background-color: #576F9E;\">\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<i class=\"i-plain i-xlarge divcenter icon-line2-graph\"></i>\r\n");
      out.write("\t\t\t\t<div class=\"counter counter-lined\"><span data-from=\"3000\" data-to=\"21500\" data-refresh-interval=\"100\" data-speed=\"2500\"></span></div>\r\n");
      out.write("\t\t\t\t<h5>등록된 인바디</h5>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"col-lg-3 col-md-6 dark center col-padding\" style=\"background-color: #6697B9;\">\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<i class=\"i-plain i-xlarge divcenter icon-line2-layers\"></i>\r\n");
      out.write("\t\t\t\t<div class=\"counter counter-lined\"><span data-from=\"10\" data-to=\"408\" data-refresh-interval=\"25\" data-speed=\"3500\"></span></div>\r\n");
      out.write("\t\t\t\t<h5>등록된 검사진단</h5>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"col-lg-3 col-md-6 dark center col-padding\" style=\"background-color: #88C3D8;\">\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<i class=\"i-plain i-xlarge divcenter icon-line2-clock\"></i>\r\n");
      out.write("\t\t\t\t<div class=\"counter counter-lined\"><span data-from=\"60\" data-to=\"1400\" data-refresh-interval=\"30\" data-speed=\"2700\"></span></div>\r\n");
      out.write("\t\t\t\t<h5>예약된 인원</h5>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"clear\"></div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container clearfix\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"col_one_third bottommargin-sm center\">\r\n");
      out.write("\t\t\t<img data-animate=\"fadeInLeft\" src=\"images/services/iphone6.png\" alt=\"Iphone\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"col_two_third bottommargin-sm col_last\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"heading-block topmargin-sm\">\r\n");
      out.write("\t\t\t\t<h3>Optimized for Mobile &amp; Touch Enabled Devices.</h3>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero quod consequuntur quibusdam, enim expedita sed quia nesciunt incidunt accusamus necessitatibus modi adipisci officia libero accusantium esse hic, obcaecati, ullam, laboriosam!</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti vero, animi suscipit id facere officia. Aspernatur, quo, quos nisi dolorum aperiam fugiat deserunt velit rerum laudantium cum magnam.</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"button button-border button-dark button-rounded button-large noleftmargin topmargin-sm\">Learn more</a>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"section\">\r\n");
      out.write("\t\t\t<div class=\"container clearfix\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"heading-block topmargin-sm center\">\r\n");
      out.write("\t\t\t\t\t<h3>회사 대표</h3>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-3 col-md-6 bottommargin\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"team\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"team-image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"images/team/4.jpg\" alt=\"John Doe\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"team-desc team-desc-bg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"team-title\"><h4>김대표</h4><span>CEO</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"social-icon inline-block si-small si-light si-rounded si-facebook\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"icon-facebook\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"icon-facebook\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"social-icon inline-block si-small si-light si-rounded si-twitter\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"icon-twitter\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"icon-twitter\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"social-icon inline-block si-small si-light si-rounded si-gplus\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"icon-gplus\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"icon-gplus\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-3 col-md-6 bottommargin\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"team\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"team-image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"images/team/2.jpg\" alt=\"Josh Clark\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"team-desc team-desc-bg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"team-title\"><h4>박영양</h4><span>영양관리사</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"social-icon inline-block si-small si-light si-rounded si-facebook\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"icon-facebook\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"icon-facebook\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"social-icon inline-block si-small si-light si-rounded si-twitter\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"icon-twitter\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"icon-twitter\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"social-icon inline-block si-small si-light si-rounded si-gplus\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"icon-gplus\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"icon-gplus\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-3 col-md-6 bottommargin\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"team\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"team-image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"images/team/8.jpg\" alt=\"Mary Jane\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"team-desc team-desc-bg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"team-title\"><h4>넌헬스</h4><span>헬스트레이너</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"social-icon inline-block si-small si-light si-rounded si-facebook\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"icon-facebook\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"icon-facebook\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"social-icon inline-block si-small si-light si-rounded si-twitter\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"icon-twitter\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"icon-twitter\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"social-icon inline-block si-small si-light si-rounded si-gplus\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"icon-gplus\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"icon-gplus\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-3 col-md-6 bottommargin\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"team\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"team-image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"images/team/3.jpg\" alt=\"Nix Maxwell\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"team-desc team-desc-bg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"team-title\"><h4>난의사</h4><span>진료의사</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"social-icon inline-block si-small si-light si-rounded si-facebook\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"icon-facebook\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"icon-facebook\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"social-icon inline-block si-small si-light si-rounded si-twitter\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"icon-twitter\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"icon-twitter\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"social-icon inline-block si-small si-light si-rounded si-gplus\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"icon-gplus\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"icon-gplus\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</section><!-- #content end -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
