/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.2
 * Generated at: 2018-12-04 08:01:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.comn.default_;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class default_002dfooter_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!-- Footer\r\n");
      out.write("\t\t============================================= -->\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$('#signUp1').click(function() {\r\n");
      out.write("\t\t\tlocation.href = \"signUp.do\";\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#btnLogin').click(function(){\r\n");
      out.write("\t\t\t$('#f').attr('action', '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/memberLogin');\r\n");
      out.write("\t\t\t$('#f').submit();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<footer id=\"footer\" class=\"dark\">\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Footer Widgets\r\n");
      out.write("\t\t============================================= -->\r\n");
      out.write("\t\t<div class=\"footer-widgets-wrap clearfix\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col_two_third\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col_one\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"widget clearfix\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/footer-widget-logo.png\" alt=\"\" class=\"footer-logo\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<p>We believe in <strong>Simple</strong>, <strong>Creative</strong> &amp; <strong>Flexible</strong> Design Standards.</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div style=\"background: url('images/world-map.png') no-repeat center center; background-size: 100%;\">\r\n");
      out.write("\t\t\t\t\t\t\t<address>\r\n");
      out.write("\t\t\t\t\t\t\t\t<strong>Headquarters:</strong><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t795 Folsom Ave, Suite 600<br>\r\n");
      out.write("\t\t\t\t\t\t\t\tSan Francisco, CA 94107<br>\r\n");
      out.write("\t\t\t\t\t\t\t</address>\r\n");
      out.write("\t\t\t\t\t\t\t<abbr title=\"Phone Number\"><strong>Phone:</strong></abbr> (91) 8547 632521<br>\r\n");
      out.write("\t\t\t\t\t\t\t<abbr title=\"Fax\"><strong>Fax:</strong></abbr> (91) 11 4752 1433<br>\r\n");
      out.write("\t\t\t\t\t\t\t<abbr title=\"Email Address\"><strong>Email:</strong></abbr> info@canvas.com\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col_one_third col_last\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"widget clearfix\" style=\"margin-bottom: -20px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-6 bottommargin-sm\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"counter counter-small\"><span data-from=\"0\" data-to=\"15065421\" data-refresh-interval=\"80\" data-speed=\"3000\" data-comma=\"true\"></span></div>\r\n");
      out.write("\t\t\t\t\t\t\t<h5 class=\"nobottommargin\">가입된 총인원</h5>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-6 bottommargin-sm\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"counter counter-small\"><span data-from=\"0\" data-to=\"5\" data-refresh-interval=\"4\" data-speed=\"2000\" data-comma=\"true\"></span></div>\r\n");
      out.write("\t\t\t\t\t\t\t<h5 class=\"nobottommargin\">관리 전문가</h5>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"widget clearfix\" style=\"margin-bottom: -20px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-6 clearfix bottommargin-sm\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"social-icon si-dark si-colored si-facebook nobottommargin\" style=\"margin-right: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"icon-facebook\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"icon-facebook\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"><small style=\"display: block; margin-top: 3px;\"><strong>Like us</strong><br>on Facebook</small></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-6 clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"social-icon si-dark si-colored si-rss nobottommargin\" style=\"margin-right: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"icon-rss\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"icon-rss\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"><small style=\"display: block; margin-top: 3px;\"><strong>Subscribe</strong><br>to RSS Feeds</small></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div><!-- .footer-widgets-wrap end -->\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Copyrights\r\n");
      out.write("\t============================================= -->\r\n");
      out.write("\t<div id=\"copyrights\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"container clearfix\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col_half\">\r\n");
      out.write("\t\t\t\tCopyrights &copy; 2014 All Rights Reserved by Canvas Inc.<br>\r\n");
      out.write("\t\t\t\t<div class=\"copyright-links\"><a href=\"#\">Terms of Use</a> / <a href=\"#\">Privacy Policy</a></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col_half col_last tright\">\r\n");
      out.write("\t\t\t\t<div class=\"fright clearfix\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"social-icon si-small si-borderless si-facebook\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"icon-facebook\"></i>\r\n");
      out.write("\t\t\t\t\t\t<i class=\"icon-facebook\"></i>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"social-icon si-small si-borderless si-twitter\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"icon-twitter\"></i>\r\n");
      out.write("\t\t\t\t\t\t<i class=\"icon-twitter\"></i>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"social-icon si-small si-borderless si-gplus\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"icon-gplus\"></i>\r\n");
      out.write("\t\t\t\t\t\t<i class=\"icon-gplus\"></i>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"social-icon si-small si-borderless si-pinterest\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"icon-pinterest\"></i>\r\n");
      out.write("\t\t\t\t\t\t<i class=\"icon-pinterest\"></i>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"social-icon si-small si-borderless si-vimeo\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"icon-vimeo\"></i>\r\n");
      out.write("\t\t\t\t\t\t<i class=\"icon-vimeo\"></i>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"social-icon si-small si-borderless si-github\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"icon-github\"></i>\r\n");
      out.write("\t\t\t\t\t\t<i class=\"icon-github\"></i>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"social-icon si-small si-borderless si-yahoo\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"icon-yahoo\"></i>\r\n");
      out.write("\t\t\t\t\t\t<i class=\"icon-yahoo\"></i>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"social-icon si-small si-borderless si-linkedin\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"icon-linkedin\"></i>\r\n");
      out.write("\t\t\t\t\t\t<i class=\"icon-linkedin\"></i>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<i class=\"icon-envelope2\"></i> info@canvas.com <span class=\"middot\">&middot;</span> <i class=\"icon-headphones\"></i> +91-11-6541-6369 <span class=\"middot\">&middot;</span> <i class=\"icon-skype2\"></i> CanvasOnSkype\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div><!-- #copyrights end -->\r\n");
      out.write("\t\r\n");
      out.write("</footer><!-- #footer end -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal\" id=\"myModal\">\r\n");
      out.write("   <div class=\"modal-dialog\">\r\n");
      out.write("     <div class=\"modal-content\" style=\" top: 241px; \">\r\n");
      out.write("     \r\n");
      out.write("       <!-- Modal Header -->\r\n");
      out.write("       <div class=\"modal-header\">\r\n");
      out.write("         <h4 class=\"modal-title\">건강 관리를 시작하세요!</h4>\r\n");
      out.write("         <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("       </div>\r\n");
      out.write("       \r\n");
      out.write("       <!-- Modal body -->\r\n");
      out.write("       <div class=\"modal-body\">\r\n");
      out.write("         \t<div>\r\n");
      out.write("\t\t\t\t<h4 class=\"uppercase ls1\"><font style=\"vertical-align: inherit;\"><font style=\"vertical-align: inherit;\">로그인</font></font></h4>\r\n");
      out.write("\t\t\t\t<form class=\"clearfix\" style=\"max-width: 300px;\" method=\"post\" id=\"f\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col_full\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"\" class=\"capitalize t600\"><font style=\"vertical-align: inherit;\"><font style=\"vertical-align: inherit;\">아이디</font></font></label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"id\" id=\"id\" class=\"sm-form-control\" autocomplete=off>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col_full\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"\" class=\"capitalize t600\"><font style=\"vertical-align: inherit;\"><font style=\"vertical-align: inherit;\">비밀번호</font></font></label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" id=\"pwd\"\" name=\"pwd\" class=\"sm-form-control\" autocomplete=off>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col_full nobottommargin\">\r\n");
      out.write("\t\t\t\t\t\t<button id=\"btnLogin\" type=\"submit\" class=\"button button-rounded button-small button-dark nomargin\" value=\"submit\"><font style=\"vertical-align: inherit;\"><font style=\"vertical-align: inherit;\">로그인</font></font></button>\r\n");
      out.write("\t\t\t\t\t\t<button id=\"signUp1\" type=\"button\" class=\"button button-rounded button-small button-dark nomargin\" value=\"submit\"><font style=\"vertical-align: inherit;\"><font style=\"vertical-align: inherit;\">신청하러가기</font></font></button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("       </div>\r\n");
      out.write("       \r\n");
      out.write("       <!-- Modal footer -->\r\n");
      out.write("       <div class=\"modal-footer\">\r\n");
      out.write("         <button type=\"button\" class=\"btn btn-danger\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("       </div>\r\n");
      out.write("       \r\n");
      out.write("     </div>\r\n");
      out.write("   </div>\r\n");
      out.write(" </div>\r\n");
      out.write("\r\n");
      out.write(" <!-- Go To Top\r\n");
      out.write("\t============================================= -->\r\n");
      out.write("\t<div id=\"gotoTop\" class=\"icon-angle-up\"></div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- External JavaScripts\r\n");
      out.write("\t============================================= -->\r\n");
      out.write("\t<script src=\"js/jquery.js\"></script>\r\n");
      out.write("\t<script src=\"js/plugins.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Footer Scripts\r\n");
      out.write("\t============================================= -->\r\n");
      out.write("\t<script src=\"js/functions.js\"></script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
