/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.2
 * Generated at: 2018-12-04 08:01:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.exercise;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class exercise_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<section id=\"page-title\" class=\"page-title-parallax page-title-dark\"\r\n");
      out.write("\tstyle=\"padding: 250px 0; background-image: url('images/about/parallax.jpg'); background-size: cover; background-position: center center;\"\r\n");
      out.write("\tdata-bottom-top=\"background-position:0px 400px;\"\r\n");
      out.write("\tdata-top-bottom=\"background-position:0px -500px;\">\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container clearfix\">\r\n");
      out.write("\t\t<h1>ANIFIT</h1>\r\n");
      out.write("\t\t<span>최고의 가성비로 누구나 건강을 관리할 수 있습니다.</span>\r\n");
      out.write("\t\t<ol class=\"breadcrumb\">\r\n");
      out.write("\t\t\t<li class=\"breadcrumb-item\"><a href=\"main.do\">Home</a></li>\r\n");
      out.write("\t\t\t<li class=\"breadcrumb-item\"><a href=\"#\">ANIFIT</a></li>\r\n");
      out.write("\t\t\t<li class=\"breadcrumb-item active\" aria-current=\"page\"><a\r\n");
      out.write("\t\t\t\thref=\"login.do\">운동법</a></li>\r\n");
      out.write("\t\t</ol>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("<!-- #page-title end -->\r\n");
      out.write("\r\n");
      out.write("<!-- Content\r\n");
      out.write("\t\t============================================= -->\r\n");
      out.write("<section id=\"content\">\r\n");
      out.write("\t<div class=\"content-wrap\">\r\n");
      out.write("\t\t<div class=\"container clearfix\" style=\"margin-bottom: 175px;\">\r\n");
      out.write("\t\t\t<h2 style=\" color: mediumvioletred; \">박노율 고객님의 운동 계획</h2>\r\n");
      out.write("\t\t\t<p style=\"float:left\"><label for=\"dp-de2\">선택된 날짜</label> : <input type=\"text\" class=\"w16em\" id=\"dp-de2\" name=\"dp-de2\" value=\"\" /></p> \r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t// <![CDATA[  \r\n");
      out.write("\t\t\t  var opts = {                            \r\n");
      out.write("\t\t\t          formElements:{\"dp-de2\":\"d-sl-m-sl-Y\"},\r\n");
      out.write("\t\t\t          showWeeks:true,\r\n");
      out.write("\t\t\t          statusFormat:\"l-cc-sp-d-sp-F-sp-Y\",\r\n");
      out.write("\t\t\t          staticPos:true,\r\n");
      out.write("\t\t\t          finalOpacity:90                  \r\n");
      out.write("\t\t\t          };           \r\n");
      out.write("\t\t\t  datePickerController.createDatePicker(opts);\r\n");
      out.write("\t\t\t// ]]>\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div style=\"float:left;width: 743px;margin-left: 49px;\">\r\n");
      out.write("\t\t\t\t<div class=\"tabs tabs-bordered clearfix\" id=\"tab-2\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t<ul class=\"tab-nav clearfix\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#tabs-5\"><i class=\"icon-home2 norightmargin\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#tabs-6\">아침</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#tabs-7\">점심</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"hidden-phone\"><a href=\"#tabs-8\">저녁</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"tab-container\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tab-content clearfix\" id=\"tabs-5\">\r\n");
      out.write("\t\t\t\t\t\t\t매일 새로운 운동법을 알려드립니다. 해당하는 시간을 클릭하시오.\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tab-content clearfix\" id=\"tabs-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/uhC2Vjle8vU\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>\r\n");
      out.write("\t\t\t\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"button button-3d button-rounded button-amber\">취소</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"button button-3d button-rounded\">체크</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"button button-3d button-mini button-rounded button-green\">미션완료</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"button button-3d button-mini button-rounded button-teal\">미션실패</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tab-content clearfix\" id=\"tabs-7\">\r\n");
      out.write("\t\t\t\t\t\t\t<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/3hhaXS4_NnI\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>\r\n");
      out.write("\t\t\t\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"button button-3d button-rounded button-amber\">취소</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tab-content clearfix\" id=\"tabs-8\">\r\n");
      out.write("\t\t\t\t\t\t\t<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/joh777Z8FBI\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>\r\n");
      out.write("\t\t\t\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"button button-3d button-rounded button-amber\">취소</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"line\"></div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("</section>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
