/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.2
 * Generated at: 2018-12-05 06:13:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/git/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SpringProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1543909372415L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("<!-- Begin Page Header-->\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("    <div class=\"page-header\">\r\n");
      out.write("     <div class=\"d-flex align-items-center\">\r\n");
      out.write("         <h2 class=\"page-header-title\">Dashboard</h2>\r\n");
      out.write("     </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"row flex-row\">\r\n");
      out.write("    <div class=\"col-xl-12 col-md-6\">\r\n");
      out.write("        <!-- Begin Widget 09 -->\r\n");
      out.write("        <div class=\"widget widget-09 has-shadow\">\r\n");
      out.write("            <!-- Begin Widget Header -->\r\n");
      out.write("            <div class=\"widget-header d-flex align-items-center\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- End Widget Header -->\r\n");
      out.write("            <!-- Begin Widget Body -->\r\n");
      out.write("            <div class=\"widget-body\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-xl-10 col-12 no-padding\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <canvas id=\"orders\"></canvas>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xl-2 col-12 d-flex flex-column my-auto no-padding text-center\">\r\n");
      out.write("                        <div class=\"some-stats mt-5\">\r\n");
      out.write("                            <div class=\"title\">총 수익</div>\r\n");
      out.write("                            <div class=\"number text-blue\">4800만원</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"some-stats mt-3\">\r\n");
      out.write("                            <div class=\"title\">총 가입자</div>\r\n");
      out.write("                            <div class=\"number text-blue\">100명</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End Widget 09 -->\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"row flex-row\">\r\n");
      out.write("    <div class=\"col-xl-12\">\r\n");
      out.write("        <!-- Begin Widget 07 -->\r\n");
      out.write("        <div class=\"widget widget-07 has-shadow\">\r\n");
      out.write("            <!-- Begin Widget Header -->\r\n");
      out.write("            <div class=\"widget-header bordered d-flex align-items-center\">\r\n");
      out.write("                <h2>1:1문의</h2>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-12 col-md-12 left\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"sorting-table_filter\" class=\"dataTables_filter\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>Search:<input type=\"search\" class=\"form-control form-control-sm\" placeholder=\"\" aria-controls=\"sorting-table\"></label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- End Widget Header -->\r\n");
      out.write("            <!-- Begin Widget Body -->\r\n");
      out.write("            <div class=\"widget-body\">\r\n");
      out.write("                <div class=\"table-responsive table-scroll padding-right-10\" style=\"max-height:520px;\">\r\n");
      out.write("                    <table class=\"table table-hover mb-0\">\r\n");
      out.write("                        <thead>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th>번호</th>\r\n");
      out.write("                                <th>아이디</th>\r\n");
      out.write("                                <th>날짜</th>\r\n");
      out.write("                                <th>작성 / 취소</th>\r\n");
      out.write("                                <th></th>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                        <tbody>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td><span class=\"text-primary\">054-01-FR</span></td>\r\n");
      out.write("                                <td>Lori Baker</td>\r\n");
      out.write("                                <td>10/21/2017</td>\r\n");
      out.write("                                <td class=\"td-actions\">\r\n");
      out.write("                                    <a href=\"adQa-Write11.do\"><i class=\"la la-edit edit\"></i></a>\r\n");
      out.write("                                    <a href=\"adQa-Delete11.do\"><i class=\"la la-close delete\"></i></a>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                \t<a href=\"adQa-Update11.do\"><button type=\"button\" class=\"btn btn-danger ripple mr-1 mb-2\">수정</button></a>\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td><span class=\"text-primary\">021-12-US</span></td>\r\n");
      out.write("                                <td>Lawrence Crawford</td>\r\n");
      out.write("                                <td>10/21/2017</td>\r\n");
      out.write("                                <td class=\"td-actions\">\r\n");
      out.write("                                    <a href=\"#\"><i class=\"la la-edit edit\"></i></a>\r\n");
      out.write("                                    <a href=\"#\"><i class=\"la la-close delete\"></i></a>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td><span class=\"text-primary\">189-01-RU</span></td>\r\n");
      out.write("                                <td>Samuel Walker</td>\r\n");
      out.write("                                <td>08/21/2017</td>\r\n");
      out.write("                                <td class=\"td-actions\">\r\n");
      out.write("                                    <a href=\"#\"><i class=\"la la-edit edit\"></i></a>\r\n");
      out.write("                                    <a href=\"#\"><i class=\"la la-close delete\"></i></a>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td><span class=\"text-primary\">092-06-FR</span></td>\r\n");
      out.write("                                <td>Angela Walters</td>\r\n");
      out.write("                                <td>08/21/2017</td>\r\n");
      out.write("                                <td class=\"td-actions\">\r\n");
      out.write("                                    <a href=\"#\"><i class=\"la la-edit edit\"></i></a>\r\n");
      out.write("                                    <a href=\"#\"><i class=\"la la-close delete\"></i></a>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td><span class=\"text-primary\">021-09-US</span></td>\r\n");
      out.write("                                <td>Ryan Hanson</td>\r\n");
      out.write("                                <td>07/21/2017</td>\r\n");
      out.write("                                <td class=\"td-actions\">\r\n");
      out.write("                                    <a href=\"#\"><i class=\"la la-edit edit\"></i></a>\r\n");
      out.write("                                    <a href=\"#\"><i class=\"la la-close delete\"></i></a>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td><span class=\"text-primary\">054-01-FR</span></td>\r\n");
      out.write("                                <td>Evelyn Black</td>\r\n");
      out.write("                                <td>10/21/2017</td>\r\n");
      out.write("                                <td class=\"td-actions\">\r\n");
      out.write("                                    <a href=\"#\"><i class=\"la la-edit edit\"></i></a>\r\n");
      out.write("                                    <a href=\"#\"><i class=\"la la-close delete\"></i></a>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td><span class=\"text-primary\">021-12-US</span></td>\r\n");
      out.write("                                <td>James Morris</td>\r\n");
      out.write("                                <td>10/21/2017</td>\r\n");
      out.write("                                <td class=\"td-actions\">\r\n");
      out.write("                                    <a href=\"#\"><i class=\"la la-edit edit\"></i></a>\r\n");
      out.write("                                    <a href=\"#\"><i class=\"la la-close delete\"></i></a>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td><span class=\"text-primary\">189-01-RU</span></td>\r\n");
      out.write("                                <td>Valentin H.</td>\r\n");
      out.write("                                <td>08/21/2017</td>\r\n");
      out.write("                                <td class=\"td-actions\">\r\n");
      out.write("                                    <a href=\"#\"><i class=\"la la-edit edit\"></i></a>\r\n");
      out.write("                                    <a href=\"#\"><i class=\"la la-close delete\"></i></a>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td><span class=\"text-primary\">092-06-FR</span></td>\r\n");
      out.write("                                <td>Beverly Matthews</td>\r\n");
      out.write("                                <td>08/21/2017</td>\r\n");
      out.write("                                <td class=\"td-actions\">\r\n");
      out.write("                                    <a href=\"#\"><i class=\"la la-edit edit\"></i></a>\r\n");
      out.write("                                    <a href=\"#\"><i class=\"la la-close delete\"></i></a>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td><span class=\"text-primary\">021-09-US</span></td>\r\n");
      out.write("                                <td>Jeffrey Arnold</td>\r\n");
      out.write("                                <td>07/21/2017</td>\r\n");
      out.write("                                <td class=\"td-actions\">\r\n");
      out.write("                                    <a href=\"#\"><i class=\"la la-edit edit\"></i></a>\r\n");
      out.write("                                    <a href=\"#\"><i class=\"la la-close delete\"></i></a>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- End Widget Body -->\r\n");
      out.write("            <!-- Begin Widget Footer -->\r\n");
      out.write("            <div class=\"widget-footer d-flex align-items-center\">\r\n");
      out.write("                <div class=\"mr-auto p-2\">\r\n");
      out.write("                    <span class=\"display-items\">\r\n");
      out.write("                    \t<button type=\"button\" class=\"btn btn-secondary btn-square mr-1 mb-2\">전체보기</button>\r\n");
      out.write("                    \t<button type=\"button\" class=\"btn btn-danger btn-square mr-1 mb-2\">대기</button>\r\n");
      out.write("                    \t<button type=\"button\" class=\"btn btn-success btn-square mr-1 mb-2\">완료</button>\r\n");
      out.write("                    </span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"p-2\">\r\n");
      out.write("                    <nav aria-label=\"...\">\r\n");
      out.write("                        <ul class=\"pagination justify-content-end\">\r\n");
      out.write("                            <li class=\"page-item disabled\">\r\n");
      out.write("                                <span class=\"page-link\"><i class=\"ion-chevron-left\"></i></span>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"page-item\"><a class=\"page-link\" href=\"#\">1</a></li>\r\n");
      out.write("                            <li class=\"page-item active\">\r\n");
      out.write("                                <span class=\"page-link\">2<span class=\"sr-only\">(current)</span></span>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"page-item\"><a class=\"page-link\" href=\"#\">3</a></li>\r\n");
      out.write("                            <li class=\"page-item\">\r\n");
      out.write("                                <a class=\"page-link\" href=\"#\"><i class=\"ion-chevron-right\"></i></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- End Widget Footer -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End Widget 07 -->\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"row flex-row\">\r\n");
      out.write("    <div class=\"col-xl-12\">\r\n");
      out.write("        <!-- Begin Widget 07 -->\r\n");
      out.write("        <div class=\"widget widget-07 has-shadow\">\r\n");
      out.write("            <!-- Begin Widget Header -->\r\n");
      out.write("            <div class=\"widget-header bordered d-flex align-items-center\">\r\n");
      out.write("                <h2>Q&A</h2>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-12 col-md-12 left\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"sorting-table_filter\" class=\"dataTables_filter\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>Search:<input type=\"search\" class=\"form-control form-control-sm\" placeholder=\"\" aria-controls=\"sorting-table\"></label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- End Widget Header -->\r\n");
      out.write("            <!-- Begin Widget Body -->\r\n");
      out.write("            <div class=\"widget-body\">\r\n");
      out.write("                <div class=\"table-responsive table-scroll padding-right-10\" style=\"max-height:520px;\">\r\n");
      out.write("                    <table class=\"table table-hover mb-0\">\r\n");
      out.write("                        <thead>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th>번호</th>\r\n");
      out.write("                                <th>제목</th>\r\n");
      out.write("                                <th>날짜</th>\r\n");
      out.write("                                <th>삭제</th>\r\n");
      out.write("                                <th></th>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                        <tbody>\r\n");
      out.write("                        \t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- End Widget Body -->\r\n");
      out.write("            <!-- Begin Widget Footer -->\r\n");
      out.write("            <div class=\"widget-footer d-flex align-items-center\">\r\n");
      out.write("                <div class=\"mr-auto p-2\">\r\n");
      out.write("                    <span class=\"display-items\">\r\n");
      out.write("                    \t<a href=\"adQaWriteForm.do\"><button type=\"button\" class=\"btn btn-success btn-square mr-1 mb-2\">작성</button></a>\r\n");
      out.write("                    </span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"p-2\">\r\n");
      out.write("                    <nav aria-label=\"...\">\r\n");
      out.write("                        <ul class=\"pagination justify-content-end\">\r\n");
      out.write("                            <li class=\"page-item disabled\">\r\n");
      out.write("                                <span class=\"page-link\"><i class=\"ion-chevron-left\"></i></span>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"page-item\"><a class=\"page-link\" href=\"#\">1</a></li>\r\n");
      out.write("                            <li class=\"page-item active\">\r\n");
      out.write("                                <span class=\"page-link\">2<span class=\"sr-only\">(current)</span></span>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"page-item\"><a class=\"page-link\" href=\"#\">3</a></li>\r\n");
      out.write("                            <li class=\"page-item\">\r\n");
      out.write("                                <a class=\"page-link\" href=\"#\"><i class=\"ion-chevron-right\"></i></a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- End Widget Footer -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End Widget 07 -->\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"assets/js/dashboard/db-default2.js\"></script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/admin/admin.jsp(247,25) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("qaList");
      // /WEB-INF/views/admin/admin.jsp(247,25) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/admin/admin.jsp(247,25) '${qaList }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${qaList }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                            <tr>\r\n");
            out.write("                                <td><span class=\"text-primary\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qaList.q_num }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span></td>\r\n");
            out.write("                                <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qaList.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                                <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qaList.reg_date }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                                <td class=\"td-actions\">\r\n");
            out.write("                                    <a href=\"qaDelete.do?q_num=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qaList.q_num }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"><i class=\"la la-close delete\"></i></a>\r\n");
            out.write("                                </td>\r\n");
            out.write("                                <td>\r\n");
            out.write("                                \t<a href=\"qaUpdateForm.do?q_num=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qaList.q_num }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"><button type=\"button\" class=\"btn btn-danger ripple mr-1 mb-2\">수정</button></a>\r\n");
            out.write("                                </td>\r\n");
            out.write("                            </tr>\r\n");
            out.write("                            ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
