/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.2
 * Generated at: 2018-12-04 06:10:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.intro;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class intro_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<section id=\"page-title\" class=\"page-title-parallax page-title-dark\" style=\"padding: 250px 0; background-image: url('images/about/parallax.jpg'); background-size: cover; background-position: center center;\" data-bottom-top=\"background-position:0px 400px;\" data-top-bottom=\"background-position:0px -500px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"container clearfix\">\r\n");
      out.write("\t\t\t\t<h1>ANIFIX</h1>\r\n");
      out.write("\t\t\t\t<span>최고의 가성비로 누구나 건강을 관리할 수 있습니다.</span>\r\n");
      out.write("\t\t\t\t<ol class=\"breadcrumb\">\r\n");
      out.write("\t\t\t\t\t<li class=\"breadcrumb-item\"><a href=\"main.do\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"breadcrumb-item\"><a href=\"#\">ANIFIT</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"breadcrumb-item active\" aria-current=\"page\"><a href=\"intro.do\">소개</a></li>\r\n");
      out.write("\t\t\t\t</ol>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</section><!-- #page-title end -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Content\r\n");
      out.write("\t\t============================================= -->\r\n");
      out.write("\t\t<section id=\"content\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"content-wrap\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"container clearfix\" style=\"margin-bottom: 175px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col_one\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"heading-block fancy-title nobottomborder title-bottom-border\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4> <span>KITRI</span>파이널 프로젝트</h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<p>애니픽트는 회원의 건강을 체크하는 솔루션입니다. 시간이 지나면서 고령화 사회는 점점 심해지고, 모든 사람들은 건강을 필요로 합니다. 이 홈페이지는 미래에 꼭 필요한 홈페이지입니다. 회원들의 직접 건강을 체크하고 체질에 맞는 건강관리를 해줍니다. </p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row common-height clearfix\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-5 col-padding\" style=\"background: url('images/team/NohYul.jpg') center center no-repeat; background-size: cover;\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-7 col-padding\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"heading-block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"before-heading color\">자바 개발자</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>박노율</h3>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row clearfix\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Employment respond committed meaningful fight against oppression social challenges rural legal aid governance. Meaningful work, implementation, process cooperation, campaign inspire.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Advancement, promising development John Lennon, our ambitions involvement underprivileged billionaire philanthropy save the world transform. Carbon rights maintain healthcare emergent, implementation inspire social change solve clean water livelihoods.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"https://www.facebook.com/profile.php?id=100003173110259\" class=\"social-icon inline-block si-small si-light si-rounded si-facebook\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"icon-facebook\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"icon-facebook\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"skills\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li data-percent=\"80\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>HTML</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress-percent\"><div class=\"counter counter-inherit counter-instant\"><span data-from=\"0\" data-to=\"60\" data-refresh-interval=\"30\" data-speed=\"1100\"></span>%</div></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li data-percent=\"60\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>CSS</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress-percent\"><div class=\"counter counter-inherit counter-instant\"><span data-from=\"0\" data-to=\"60\" data-refresh-interval=\"30\" data-speed=\"1100\"></span>%</div></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li data-percent=\"90\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>JAVASCRIPT</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress-percent\"><div class=\"counter counter-inherit counter-instant\"><span data-from=\"0\" data-to=\"50\" data-refresh-interval=\"30\" data-speed=\"1100\"></span>%</div></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li data-percent=\"70\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>JAVA</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress-percent\"><div class=\"counter counter-inherit counter-instant\"><span data-from=\"0\" data-to=\"70\" data-refresh-interval=\"30\" data-speed=\"1100\"></span>%</div></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li data-percent=\"85\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>SPRING</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress-percent\"><div class=\"counter counter-inherit counter-instant\"><span data-from=\"0\" data-to=\"75\" data-refresh-interval=\"30\" data-speed=\"1100\"></span>%</div></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row common-height bottommargin-lg clearfix\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-7 col-padding\" style=\"background-color: #F5F5F5;\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"heading-block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"before-heading color\">Developer &amp; Evangelist</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>박창순</h3>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row clearfix\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Employment respond committed meaningful fight against oppression social challenges rural legal aid governance. Meaningful work, implementation, process cooperation, campaign inspire.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Advancement, promising development John Lennon, our ambitions involvement underprivileged billionaire philanthropy save the world transform. Carbon rights maintain healthcare emergent, implementation inspire social change solve clean water livelihoods.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"social-icon inline-block si-small si-light si-rounded si-facebook\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"icon-facebook\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"icon-facebook\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"social-icon inline-block si-small si-light si-rounded si-twitter\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"icon-twitter\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"icon-twitter\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"social-icon inline-block si-small si-light si-rounded si-gplus\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"icon-gplus\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"icon-gplus\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"skills\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li data-percent=\"80\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>Wordpress</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress-percent\"><div class=\"counter counter-inherit counter-instant\"><span data-from=\"0\" data-to=\"80\" data-refresh-interval=\"30\" data-speed=\"1100\"></span>%</div></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li data-percent=\"60\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>CSS3</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress-percent\"><div class=\"counter counter-inherit counter-instant\"><span data-from=\"0\" data-to=\"60\" data-refresh-interval=\"30\" data-speed=\"1100\"></span>%</div></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li data-percent=\"90\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>HTML5</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress-percent\"><div class=\"counter counter-inherit counter-instant\"><span data-from=\"0\" data-to=\"90\" data-refresh-interval=\"30\" data-speed=\"1100\"></span>%</div></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li data-percent=\"70\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>jQuery</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress-percent\"><div class=\"counter counter-inherit counter-instant\"><span data-from=\"0\" data-to=\"70\" data-refresh-interval=\"30\" data-speed=\"1100\"></span>%</div></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li data-percent=\"85\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>Ruby</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress-percent\"><div class=\"counter counter-inherit counter-instant\"><span data-from=\"0\" data-to=\"85\" data-refresh-interval=\"30\" data-speed=\"1100\"></span>%</div></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-5 col-padding\" style=\"background: url('images/team/8.jpg') center center no-repeat; background-size: cover;\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"row common-height clearfix\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-5 col-padding\" style=\"background: url('images/team/3.jpg') center center no-repeat; background-size: cover;\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-7 col-padding\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"heading-block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"before-heading color\">CEO &amp; Co-Founder</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>경규일</h3>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row clearfix\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Employment respond committed meaningful fight against oppression social challenges rural legal aid governance. Meaningful work, implementation, process cooperation, campaign inspire.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Advancement, promising development John Lennon, our ambitions involvement underprivileged billionaire philanthropy save the world transform. Carbon rights maintain healthcare emergent, implementation inspire social change solve clean water livelihoods.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"social-icon inline-block si-small si-light si-rounded si-facebook\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"icon-facebook\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"icon-facebook\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"social-icon inline-block si-small si-light si-rounded si-twitter\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"icon-twitter\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"icon-twitter\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"social-icon inline-block si-small si-light si-rounded si-gplus\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"icon-gplus\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"icon-gplus\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"skills\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li data-percent=\"80\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>Wordpress</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress-percent\"><div class=\"counter counter-inherit counter-instant\"><span data-from=\"0\" data-to=\"80\" data-refresh-interval=\"30\" data-speed=\"1100\"></span>%</div></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li data-percent=\"60\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>CSS3</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress-percent\"><div class=\"counter counter-inherit counter-instant\"><span data-from=\"0\" data-to=\"60\" data-refresh-interval=\"30\" data-speed=\"1100\"></span>%</div></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li data-percent=\"90\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>HTML5</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress-percent\"><div class=\"counter counter-inherit counter-instant\"><span data-from=\"0\" data-to=\"90\" data-refresh-interval=\"30\" data-speed=\"1100\"></span>%</div></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li data-percent=\"70\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>jQuery</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress-percent\"><div class=\"counter counter-inherit counter-instant\"><span data-from=\"0\" data-to=\"70\" data-refresh-interval=\"30\" data-speed=\"1100\"></span>%</div></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li data-percent=\"85\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>Ruby</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress-percent\"><div class=\"counter counter-inherit counter-instant\"><span data-from=\"0\" data-to=\"85\" data-refresh-interval=\"30\" data-speed=\"1100\"></span>%</div></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row common-height bottommargin-lg clearfix\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-7 col-padding\" style=\"background-color: #F5F5F5;\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"heading-block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"before-heading color\">Developer &amp; Evangelist</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>김상진</h3>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row clearfix\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Employment respond committed meaningful fight against oppression social challenges rural legal aid governance. Meaningful work, implementation, process cooperation, campaign inspire.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Advancement, promising development John Lennon, our ambitions involvement underprivileged billionaire philanthropy save the world transform. Carbon rights maintain healthcare emergent, implementation inspire social change solve clean water livelihoods.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"social-icon inline-block si-small si-light si-rounded si-facebook\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"icon-facebook\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"icon-facebook\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"social-icon inline-block si-small si-light si-rounded si-twitter\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"icon-twitter\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"icon-twitter\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"social-icon inline-block si-small si-light si-rounded si-gplus\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"icon-gplus\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"icon-gplus\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"skills\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li data-percent=\"80\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>Wordpress</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress-percent\"><div class=\"counter counter-inherit counter-instant\"><span data-from=\"0\" data-to=\"80\" data-refresh-interval=\"30\" data-speed=\"1100\"></span>%</div></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li data-percent=\"60\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>CSS3</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress-percent\"><div class=\"counter counter-inherit counter-instant\"><span data-from=\"0\" data-to=\"60\" data-refresh-interval=\"30\" data-speed=\"1100\"></span>%</div></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li data-percent=\"90\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>HTML5</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress-percent\"><div class=\"counter counter-inherit counter-instant\"><span data-from=\"0\" data-to=\"90\" data-refresh-interval=\"30\" data-speed=\"1100\"></span>%</div></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li data-percent=\"70\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>jQuery</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress-percent\"><div class=\"counter counter-inherit counter-instant\"><span data-from=\"0\" data-to=\"70\" data-refresh-interval=\"30\" data-speed=\"1100\"></span>%</div></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li data-percent=\"85\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>Ruby</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress-percent\"><div class=\"counter counter-inherit counter-instant\"><span data-from=\"0\" data-to=\"85\" data-refresh-interval=\"30\" data-speed=\"1100\"></span>%</div></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-5 col-padding\" style=\"background: url('images/team/8.jpg') center center no-repeat; background-size: cover;\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"row common-height clearfix\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-5 col-padding\" style=\"background: url('images/team/3.jpg') center center no-repeat; background-size: cover;\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-7 col-padding\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"heading-block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"before-heading color\">CEO &amp; Co-Founder</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>정한길</h3>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row clearfix\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Employment respond committed meaningful fight against oppression social challenges rural legal aid governance. Meaningful work, implementation, process cooperation, campaign inspire.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Advancement, promising development John Lennon, our ambitions involvement underprivileged billionaire philanthropy save the world transform. Carbon rights maintain healthcare emergent, implementation inspire social change solve clean water livelihoods.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"social-icon inline-block si-small si-light si-rounded si-facebook\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"icon-facebook\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"icon-facebook\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"social-icon inline-block si-small si-light si-rounded si-twitter\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"icon-twitter\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"icon-twitter\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"social-icon inline-block si-small si-light si-rounded si-gplus\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"icon-gplus\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"icon-gplus\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"skills\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li data-percent=\"80\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>Wordpress</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress-percent\"><div class=\"counter counter-inherit counter-instant\"><span data-from=\"0\" data-to=\"80\" data-refresh-interval=\"30\" data-speed=\"1100\"></span>%</div></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li data-percent=\"60\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>CSS3</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress-percent\"><div class=\"counter counter-inherit counter-instant\"><span data-from=\"0\" data-to=\"60\" data-refresh-interval=\"30\" data-speed=\"1100\"></span>%</div></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li data-percent=\"90\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>HTML5</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress-percent\"><div class=\"counter counter-inherit counter-instant\"><span data-from=\"0\" data-to=\"90\" data-refresh-interval=\"30\" data-speed=\"1100\"></span>%</div></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li data-percent=\"70\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>jQuery</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress-percent\"><div class=\"counter counter-inherit counter-instant\"><span data-from=\"0\" data-to=\"70\" data-refresh-interval=\"30\" data-speed=\"1100\"></span>%</div></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li data-percent=\"85\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>Ruby</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"progress-percent\"><div class=\"counter counter-inherit counter-instant\"><span data-from=\"0\" data-to=\"85\" data-refresh-interval=\"30\" data-speed=\"1100\"></span>%</div></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</section><!-- #content end -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
