/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.2
 * Generated at: 2018-12-04 08:01:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signUp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"//code.jquery.com/jquery-3.3.1.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t$('#btnAdd').click(function(){\r\n");
      out.write("\t\t\tvar id = $('#id').val();\r\n");
      out.write("\t\t\tif(id=='' || id==null){\r\n");
      out.write("\t\t\t\talert('id를 입력하세요');\r\n");
      out.write("\t\t\t\treturn ;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$('#f').attr('action', '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/memberAdd');\r\n");
      out.write("\t\t\t$('#f').submit();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 패스워드 일치 체크 */\r\n");
      out.write("\t\t$('#pwd').change(function() {\r\n");
      out.write("\t\t\tvar pwd = $('#pwd').val();\r\n");
      out.write("\t\t\tvar pwdCheck = $('#pwdCheck').val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif (pwd == pwdCheck) {\r\n");
      out.write("\t\t\t\t$('#check').css('display','none');\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$('#check').css('display','');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$('#pwdCheck').change(function() {\r\n");
      out.write("\t\t\tvar pwd = $('#pwd').val();\r\n");
      out.write("\t\t\tvar pwdCheck = $('#pwdCheck').val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif (pwd == pwdCheck) {\r\n");
      out.write("\t\t\t\t$('#check').css('display','none');\r\n");
      out.write("\t\t\t}else {\r\n");
      out.write("\t\t\t\t$('#check').css('display','');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* id 중복체크 */\r\n");
      out.write("\t\t$('#id').change(function(){\r\n");
      out.write("\t\t\tvar id = $('#id').val();\r\n");
      out.write("\t\t\tvar param = \"id=\"+id;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype:\"POST\",\r\n");
      out.write("\t\t\t\turl:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/memberIdCheck\",\r\n");
      out.write("\t\t\t\tdata:param,\r\n");
      out.write("\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\tvar obj = eval('('+data+')');\r\n");
      out.write("\t\t\t\t\tif(obj.flag){\t// 사용 가능한 아이디\r\n");
      out.write("\t\t\t\t\t\t$('#idCheckSuccess').css('display','');\r\n");
      out.write("\t\t\t\t\t\t$('#idCheckFail').css('display','none');\r\n");
      out.write("\t\t\t\t\t} else {\t// 중복된 아이디\r\n");
      out.write("\t\t\t\t\t\t$('#idCheckFail').css('display','');\r\n");
      out.write("\t\t\t\t\t\t$('#idCheckSuccess').css('display','none');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<section id=\"page-title\" class=\"page-title-parallax page-title-dark\" style=\"padding: 250px 0; background-image: url('images/about/parallax.jpg'); background-size: cover; background-position: center center;\" data-bottom-top=\"background-position:0px 400px;\" data-top-bottom=\"background-position:0px -500px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"container clearfix\">\r\n");
      out.write("\t\t\t\t<h1>ANIFIT</h1>\r\n");
      out.write("\t\t\t\t<span>최고의 가성비로 누구나 건강을 관리할 수 있습니다.</span>\r\n");
      out.write("\t\t\t\t<ol class=\"breadcrumb\">\r\n");
      out.write("\t\t\t\t\t<li class=\"breadcrumb-item\"><a href=\"main.do\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"breadcrumb-item\"><a href=\"#\">ANIFIT</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"breadcrumb-item active\" aria-current=\"page\"><a href=\"signUp.do\">신청</a></li>\r\n");
      out.write("\t\t\t\t</ol>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</section><!-- #page-title end -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Content\r\n");
      out.write("\t\t============================================= -->\r\n");
      out.write("\t\t<section id=\"content\">\r\n");
      out.write("\t\t\t<div class=\"content-wrap\">\r\n");
      out.write("\t\t\t\t<div class=\"container clearfix\" style=\"margin-bottom: 175px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col_one\">\r\n");
      out.write("\t\t\t\t\t\t<h3>신청 하기</h3>\r\n");
      out.write("\t\t\t\t\t\t<form style=\"max-width: 25rem;\" id=\"f\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"exampleInputId\">아이디</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"id\" name=\"id\" type=\"text\" class=\"form-control\" aria-describedby=\"emailHelp\" placeholder=\"Enter id\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"style-msg alertmsg\" style=\"display:none;\" id=\"idCheckFail\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"sb-msg\"><i class=\"icon-warning-sign\"></i><strong>경고!</strong> 이미 존재하는 아이디입니다.</div> \r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"style-msg successmsg\" style=\"display:none;\" id=\"idCheckSuccess\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"sb-msg\"><i class=\"icon-thumbs-up\"></i><strong>사용가능</strong> 사용할 수 있는 아이디입니다.</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"exampleInputPassword1\">비밀번호</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" id=\"pwd\" name=\"pwd\" placeholder=\"Password\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"exampleInputPasswordCheck\">비밀번호체크</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" id=\"pwdCheck\" placeholder=\"PasswordCheck\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"style-msg alertmsg\" id='check'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"sb-msg\"><i class=\"icon-warning-sign\"></i><strong>경고!</strong> 비밀번호가 일치하지 않습니다.</div> \r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"exampleInputName\">이름</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"name\" id=\"name\" placeholder=\"Name\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"exampleInputTel\">전화번호</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"tel\" name=\"tel\" placeholder=\"Tel\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"exampleInputSex\">성별</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"sex\" class=\"custom-select form-control\">\r\n");
      out.write("                                    <option>남성</option>\r\n");
      out.write("                                    <option>여성</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("                                <label for=\"exampleAge\">연령</label>\r\n");
      out.write("                                <select name=\"age\" class=\"custom-select form-control\">\r\n");
      out.write("                                    <option>10대</option>\r\n");
      out.write("                                    <option>20대</option>\r\n");
      out.write("                                    <option>30대</option>\r\n");
      out.write("                                    <option>40대</option>\r\n");
      out.write("                                    <option>50대</option>\r\n");
      out.write("                                    <option>60대</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"exampleInputEmail\">이메일</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"email\" class=\"form-control\" id=\"email\" name=\"email\" aria-describedby=\"emailHelp\" placeholder=\"Email\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"style-msg alertmsg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"sb-msg\"><i class=\"icon-warning-sign\"></i><strong>경고!</strong> 이미 존재하는 이메일 입니다.</div> \r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"exampleInputEmail\">주소</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"address\" name=\"address\" aria-describedby=\"emailHelp\" placeholder=\"Email\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"style-msg alertmsg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"sb-msg\"><i class=\"icon-warning-sign\"></i><strong>경고!</strong> 이미 존재하는 이메일 입니다.</div> \r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary mt-3\" id=\"btnAdd\">신청</button>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary mt-3\">취소</button>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section><!-- #content end -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
