/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.2
 * Generated at: 2018-12-04 08:28:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.qa11;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class qa11_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<section id=\"page-title\" class=\"page-title-parallax page-title-dark\" style=\"padding: 250px 0; background-image: url('images/about/parallax.jpg'); background-size: cover; background-position: center center;\" data-bottom-top=\"background-position:0px 400px;\" data-top-bottom=\"background-position:0px -500px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"container clearfix\">\r\n");
      out.write("\t\t\t\t<h1>ANIFIT</h1>\r\n");
      out.write("\t\t\t\t<span>최고의 가성비로 누구나 건강을 관리할 수 있습니다.</span>\r\n");
      out.write("\t\t\t\t<ol class=\"breadcrumb\">\r\n");
      out.write("\t\t\t\t\t<li class=\"breadcrumb-item\"><a href=\"main.do\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"breadcrumb-item\"><a href=\"#\">ANIFIT</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"breadcrumb-item active\" aria-current=\"page\"><a href=\"qa.do\">1:1문의</a></li>\r\n");
      out.write("\t\t\t\t</ol>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</section><!-- #page-title end -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Content\r\n");
      out.write("\t\t============================================= -->\r\n");
      out.write("\t\t<section id=\"content\">\r\n");
      out.write("\t\t\t<div class=\"content-wrap\">\r\n");
      out.write("\t\t\t\t<div class=\"container clearfix\" style=\"margin-bottom: 175px;\">\r\n");
      out.write("\t\t\t\t\t<h4>1:1 문의</h4>\r\n");
      out.write("\t\t\t\t\t<div class=\"col_one\">\r\n");
      out.write("\t\t\t\t\t\t<table class=\"table table-striped\">\r\n");
      out.write("\t\t\t\t\t\t  <thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t  <th>no</th>\r\n");
      out.write("\t\t\t\t\t\t\t  <th>Name</th>\r\n");
      out.write("\t\t\t\t\t\t\t  <th>Title</th>\r\n");
      out.write("\t\t\t\t\t\t\t  <th>Date</th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t  </thead>\r\n");
      out.write("\t\t\t\t\t\t  <tbody>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>1</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>Mark</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td><a href=\"qaDetail11.do\">Otto</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>@mdo</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>2</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>Jacob</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>Thornton</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>@fat</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>3</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>Larry</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>the Bird</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>@twitter</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"4\"><a href=\"qaWriteForm11.do\" class=\"btn btn-secondary btn-sm fright\">작성하기</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t  </tbody>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t<nav aria-label=\"Page navigation example\">\r\n");
      out.write("\t\t\t\t\t\t  <ul class=\"pagination\">\r\n");
      out.write("\t\t\t\t\t\t    <li class=\"page-item disabled\">\r\n");
      out.write("\t\t\t\t\t\t      <span class=\"page-link\">&laquo;</span>\r\n");
      out.write("\t\t\t\t\t\t    </li>\r\n");
      out.write("\t\t\t\t\t\t    <li class=\"page-item\"><a class=\"page-link\" href=\"#\">1</a></li>\r\n");
      out.write("\t\t\t\t\t\t    <li class=\"page-item active\">\r\n");
      out.write("\t\t\t\t\t\t      <span class=\"page-link\">\r\n");
      out.write("\t\t\t\t\t\t        2\r\n");
      out.write("\t\t\t\t\t\t        <span class=\"sr-only\">(current)</span>\r\n");
      out.write("\t\t\t\t\t\t      </span>\r\n");
      out.write("\t\t\t\t\t\t    </li>\r\n");
      out.write("\t\t\t\t\t\t    <li class=\"page-item\"><a class=\"page-link\" href=\"#\">3</a></li>\r\n");
      out.write("\t\t\t\t\t\t    <li class=\"page-item\">\r\n");
      out.write("\t\t\t\t\t\t      <a class=\"page-link\" href=\"#\">&raquo;</a>\r\n");
      out.write("\t\t\t\t\t\t    </li>\r\n");
      out.write("\t\t\t\t\t\t  </ul>\r\n");
      out.write("\t\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section><!-- #content end -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
