/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.2
 * Generated at: 2018-12-03 07:54:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.comn.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_002dheader_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<header class=\"header\">\r\n");
      out.write("    <nav class=\"navbar fixed-top\">         \r\n");
      out.write("        <!-- Begin Search Box-->\r\n");
      out.write("        <div class=\"search-box\">\r\n");
      out.write("            <button class=\"dismiss\"><i class=\"ion-close-round\"></i></button>\r\n");
      out.write("            <form id=\"searchForm\" action=\"#\" role=\"search\">\r\n");
      out.write("                <input type=\"search\" placeholder=\"Search something ...\" class=\"form-control\">\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End Search Box-->\r\n");
      out.write("        <!-- Begin Topbar -->\r\n");
      out.write("        <div class=\"navbar-holder d-flex align-items-center align-middle justify-content-between\">\r\n");
      out.write("            <!-- Begin Logo -->\r\n");
      out.write("            <div class=\"navbar-header\">\r\n");
      out.write("                <a href=\"main.do\" class=\"navbar-brand\">\r\n");
      out.write("                    <div class=\"brand-image brand-big\">\r\n");
      out.write("                        <img src=\"assets/img/logo-big.png\" alt=\"logo\" class=\"logo-big\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"brand-image brand-small\">\r\n");
      out.write("                        <img src=\"assets/img/logo.png\" alt=\"logo\" class=\"logo-small\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </a>\r\n");
      out.write("                <!-- Toggle Button -->\r\n");
      out.write("                <a id=\"toggle-btn\" href=\"#\" class=\"menu-btn active\">\r\n");
      out.write("                    <span></span>\r\n");
      out.write("                    <span></span>\r\n");
      out.write("                    <span></span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <!-- End Toggle -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- End Logo -->\r\n");
      out.write("            <!-- Begin Navbar Menu -->\r\n");
      out.write("            <ul class=\"nav-menu list-unstyled d-flex flex-md-row align-items-md-center pull-right\">\r\n");
      out.write("                <!-- Search -->\r\n");
      out.write("                <li class=\"nav-item d-flex align-items-center\"><a id=\"search\" href=\"#\"><i class=\"la la-search\"></i></a></li>\r\n");
      out.write("                <!-- End Search -->\r\n");
      out.write("                <!-- Begin Notifications -->\r\n");
      out.write("                <li class=\"nav-item dropdown\"><a id=\"notifications\" rel=\"nofollow\" data-target=\"#\" href=\"#\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\" class=\"nav-link\"><i class=\"la la-bell animated infinite swing\"></i><span class=\"badge-pulse\"></span></a>\r\n");
      out.write("                    <ul aria-labelledby=\"notifications\" class=\"dropdown-menu notification\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <div class=\"notifications-header\">\r\n");
      out.write("                                <div class=\"title\">예약자 대기 목록 (3)</div>\r\n");
      out.write("                                <div class=\"notifications-overlay\"></div>\r\n");
      out.write("                                <img src=\"assets/img/notifications/01.jpg\" alt=\"...\" class=\"img-fluid\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <div class=\"message-icon\">\r\n");
      out.write("                                    <i class=\"la la-user\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"message-body\">\r\n");
      out.write("                                    <div class=\"message-body-heading\">\r\n");
      out.write("                                    \t경규일\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <span class=\"date\">1 hours ago</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <div class=\"message-icon\">\r\n");
      out.write("                                    <i class=\"la la-user\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"message-body\">\r\n");
      out.write("                                    <div class=\"message-body-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t김상진\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <span class=\"date\">1 hours ago</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <div class=\"message-icon\">\r\n");
      out.write("                                    <i class=\"la la-user\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"message-body\">\r\n");
      out.write("                                    <div class=\"message-body-heading\">\r\n");
      out.write("                                    \t박창순\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <span class=\"date\">4 hours ago</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a rel=\"nofollow\" href=\"#\" class=\"dropdown-item all-notifications text-center\">View All Notifications</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <!-- End Notifications -->\r\n");
      out.write("                <!-- User -->\r\n");
      out.write("                <li class=\"nav-item dropdown\"><a id=\"user\" rel=\"nofollow\" data-target=\"#\" href=\"#\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\" class=\"nav-link\"><img src=\"assets/img/avatar/avatar-01.jpg\" alt=\"...\" class=\"avatar rounded-circle\"></a>\r\n");
      out.write("                    <ul aria-labelledby=\"user\" class=\"user-size dropdown-menu\">\r\n");
      out.write("                        <li class=\"welcome\">\r\n");
      out.write("                            <a href=\"#\" class=\"edit-profil\"><i class=\"la la-gear\"></i></a>\r\n");
      out.write("                            <img src=\"assets/img/avatar/avatar-01.jpg\" alt=\"...\" class=\"rounded-circle\">\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"separator\"></li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"pages-faq.html\" class=\"dropdown-item no-padding-top\"> \r\n");
      out.write("                                logout\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a rel=\"nofollow\" href=\"pages-login.html\" class=\"dropdown-item logout text-center\"><i class=\"ti-power-off\"></i></a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <!-- End Navbar Menu -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End Topbar -->\r\n");
      out.write("    </nav>\r\n");
      out.write("</header>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
